//! A budgeted map of the workspace, built once per session.
//!
//! Without one, an agent picks where to look by convention — the manifest,
//! the entry point, a directory listing — and convention is a poor guide in an
//! unfamiliar repository. Worse, a listing tells it a file *exists* without
//! telling it what is in it, which invites a confident guess about contents it
//! never opened.
//!
//! The map is deliberately shallow: paths and the names they declare, nothing
//! more. That is enough to turn "where might permission handling live?" into a
//! `read_file` on the right file, which is the whole job. Bodies stay out of
//! it — reading those is what the tools are for.
//!
//! It is injected into the system prompt rather than offered as a tool. A tool
//! has to be chosen, and the moment it is most needed is exactly the moment an
//! agent is least aware it needs it.

use ignore::WalkBuilder;
use std::collections::HashMap;
use std::path::{Path, PathBuf};

/// Roughly four characters per token; the map is mostly short identifiers.
const CHARS_PER_TOKEN: usize = 4;

/// Files bigger than this are almost always generated or vendored.
const MAX_FILE_BYTES: u64 = 512 * 1024;

/// Symbols listed per file before the rest are summarised as a count.
const MAX_SYMBOLS_PER_FILE: usize = 12;

/// An agent-specific ignore file, read after `.gitignore` and able to undo it.
///
/// What git ignores and what an agent should ignore are different questions
/// that happen to have similar answers most of the time. Build output and
/// dependencies belong in neither. But a generated client that everyone reads
/// and nobody commits belongs in the map, and a committed vendored library
/// does not. `.gitignore` is the right default and the wrong authority, so it
/// stays the default and this file overrules it — including with `!` patterns
/// that put a git-ignored path back on the map.
const AGENT_IGNORE: &str = ".agentignore";

/// Directories that are noise even when they are committed.
const VENDORED: &[&str] = &[
    "/vendor/",
    "/third_party/",
    "/thirdparty/",
    "/node_modules/",
    "/.venv/",
    "/site-packages/",
    "/Pods/",
    "/gen/",
    "/generated/",
];

/// Markers that tools put at the top of files they wrote.
const GENERATED_MARKERS: &[&str] = &[
    "@generated",
    "Code generated by",
    "DO NOT EDIT",
    "autogenerated",
    "auto-generated",
];

/// Does this file announce itself as machine-written?
///
/// Checked over the opening lines only: the convention is to say so at the
/// top, and scanning whole files for a phrase would be both slow and prone to
/// catching a passing mention in prose.
fn looks_generated(text: &str) -> bool {
    text.lines()
        .take(5)
        .any(|line| GENERATED_MARKERS.iter().any(|m| line.contains(m)))
}

fn is_vendored(relative: &str) -> bool {
    let padded = format!("/{relative}");
    VENDORED.iter().any(|dir| padded.contains(dir))
}

#[derive(Debug, Clone)]
struct FileEntry {
    path: String,
    symbols: Vec<String>,
    /// Higher sorts first.
    score: f64,
}

/// Build a map of `root`, at most `token_budget` tokens long.
pub fn build(root: &Path, token_budget: usize) -> String {
    let mut entries = collect(root);
    if entries.is_empty() {
        return String::new();
    }

    entries.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.path.cmp(&b.path))
    });

    render(&entries, token_budget)
}

/// Paths `.agentignore` asks to put back despite `.gitignore`.
///
/// The walker prunes an ignored directory before it ever looks inside, so a
/// `!` line cannot undo a `.gitignore` rule from within the same traversal —
/// the directory is simply never visited. Re-inclusion therefore needs its
/// own pass, rooted at each named path with git's rules switched off.
/// Granularity is the directory: `!generated/` works, `!generated/*.rs` is
/// treated as `!generated/`.
fn reincluded_roots(root: &Path) -> Vec<PathBuf> {
    let Ok(text) = std::fs::read_to_string(root.join(AGENT_IGNORE)) else {
        return Vec::new();
    };
    text.lines()
        .filter_map(|line| line.trim().strip_prefix('!'))
        .map(|pattern| {
            pattern
                .trim_matches('/')
                .split('*')
                .next()
                .unwrap_or("")
                .trim_matches('/')
        })
        .filter(|pattern| !pattern.is_empty())
        .map(|pattern| root.join(pattern))
        .filter(|path| path.is_dir())
        .collect()
}

/// The folders an operating system guards, which a walk must not wander into.
///
/// macOS puts `~/Desktop`, `~/Documents`, `~/Downloads`, `~/Music`, `~/Movies`
/// and `~/Pictures` behind TCC: the first read of one raises a system consent
/// dialog naming the program that asked. The walk meets them only when the
/// workspace *contains* them, which in practice means the workspace is the
/// home directory — the desktop app falls back to `$HOME` when Finder starts
/// it with no project to open, and the first session then mapped the lot. That
/// is one dialog per folder, from an app the user had just opened and never
/// asked to look through their music.
///
/// A map of `~/Music` was worth nothing even where it is free, so the walk
/// stops at the door on every platform rather than only where the prompt
/// appears. `dirs` is asked for the real locations, because on a localised
/// desktop they are not these English names. `~/Library` joins them on macOS:
/// partly guarded, wholly uninteresting, and enormous.
///
/// Opening one of these *as* the workspace is a different act — the user named
/// it, and a prompt they can attribute to their own click is a fair trade for
/// the map they asked for — so this prunes only what the walk descends into,
/// never the root it was handed. See [`is_guarded`].
fn guarded_dirs() -> Vec<PathBuf> {
    let mut guarded: Vec<PathBuf> = [
        dirs::desktop_dir(),
        dirs::document_dir(),
        dirs::download_dir(),
        dirs::audio_dir(),
        dirs::video_dir(),
        dirs::picture_dir(),
    ]
    .into_iter()
    .flatten()
    .collect();
    if cfg!(target_os = "macos") {
        guarded.extend(dirs::home_dir().map(|home| home.join("Library")));
    }
    guarded
}

/// Whether the walk should stop at `path` rather than descend into it.
///
/// The root is exempt on purpose: pruning it would map nothing at all, and a
/// workspace someone chose is not a folder we wandered into. A project *inside*
/// a guarded folder is likewise untouched, because the walk starts below the
/// door and never meets it.
fn is_guarded(root: &Path, path: &Path, guarded: &[PathBuf]) -> bool {
    path != root && guarded.iter().any(|dir| dir == path)
}

fn collect(root: &Path) -> Vec<FileEntry> {
    collect_within(root, guarded_dirs())
}

/// `collect`, with the guarded set passed in so a test can name one.
fn collect_within(root: &Path, guarded: Vec<PathBuf>) -> Vec<FileEntry> {
    let mut entries = Vec::new();
    let mut seen: std::collections::HashSet<PathBuf> = std::collections::HashSet::new();

    // `ignore` honours .gitignore, so generated output and vendored
    // dependencies stay out without a hand-maintained deny list.
    let walk_root = root.to_path_buf();
    let walker = WalkBuilder::new(root)
        .hidden(true)
        .git_ignore(true)
        .git_global(true)
        .parents(true)
        // Honour .gitignore even when the workspace is not itself a git
        // repository — a worktree handed to a subagent often is not, and its
        // build output should stay out of the map all the same.
        .require_git(false)
        // Read after .gitignore and therefore able to override it, in both
        // directions.
        .add_custom_ignore_filename(AGENT_IGNORE)
        .filter_entry(move |entry| !is_guarded(&walk_root, entry.path(), &guarded))
        .build();

    // The main pass, then one per re-included root.
    let reincluded = reincluded_roots(root);
    let mut passes: Vec<Box<dyn Iterator<Item = ignore::DirEntry>>> =
        vec![Box::new(walker.flatten())];
    for path in &reincluded {
        passes.push(Box::new(
            WalkBuilder::new(path)
                .hidden(true)
                .git_ignore(false)
                .git_global(false)
                .parents(false)
                .build()
                .flatten(),
        ));
    }

    for entry in passes.into_iter().flatten() {
        if !entry.file_type().is_some_and(|t| t.is_file()) {
            continue;
        }
        let path = entry.path();
        let Some(language) = language_of(path) else {
            continue;
        };
        let Ok(meta) = entry.metadata() else { continue };
        if meta.len() > MAX_FILE_BYTES {
            continue;
        }
        if !seen.insert(path.to_path_buf()) {
            continue;
        }
        let Ok(text) = std::fs::read_to_string(path) else {
            continue;
        };

        if looks_generated(&text) {
            continue;
        }

        let symbols = declarations(&text, language);
        if symbols.is_empty() {
            continue;
        }

        let relative = path
            .strip_prefix(root)
            .unwrap_or(path)
            .to_string_lossy()
            .replace('\\', "/");

        // Heuristics are a default, not a veto. Asking for a path by name in
        // `.agentignore` is a statement about this repository, and it beats a
        // guess made from a directory name — `generated/` is noise in most
        // projects and the point of the map in one that checks in a client.
        let asked_for = reincluded.iter().any(|root| path.starts_with(root));
        if !asked_for && is_vendored(&relative) {
            continue;
        }

        // Rank by how much a file declares, and nothing else.
        //
        // This was a weighted product of symbol count, file age and path
        // depth, with three invented constants. None of them could be
        // validated — there is no benchmark here to tune against — and after
        // the map stopped dropping files, ranking only decides which files
        // get their symbols spelled out first. That is a small enough job to
        // do with the obvious signal.
        entries.push(FileEntry {
            score: symbols.len() as f64,
            path: relative,
            symbols,
        });
    }
    entries
}

/// Render the map, spending the budget on detail before completeness.
///
/// The first version of this ranked files and cut the tail, which is the
/// obvious thing and the wrong one. A file missing from the map does not read
/// as "not shown"; it reads as "not there". That is how an agent came to
/// report that this project had no multimodal support — `src/llm/content.rs`
/// had been cut to save about a thousand tokens, so the agent never saw the
/// file that defines it and concluded the capability was absent.
///
/// So the order of sacrifice is inverted. Every file keeps its line; what
/// varies is how much is said about each. Only when even the bare paths will
/// not fit does the map drop to naming directories and their file counts —
/// still complete at that level, still never implying an absence.
fn render(entries: &[FileEntry], token_budget: usize) -> String {
    let header = "## Repository map\n\nWhat each file declares. Symbol lists are abbreviated on lower-ranked \
files, but every file is listed: if a path is not here, it is not in the \
workspace. Open a file before claiming what it does.\n\n";

    let mut budget = token_budget
        .saturating_mul(CHARS_PER_TOKEN)
        .saturating_sub(header.len());

    // Group by directory, keeping each group in rank order.
    let mut queues: Vec<(&str, Vec<&FileEntry>)> = Vec::new();
    for entry in entries {
        let dir = entry.path.rsplit_once('/').map(|(d, _)| d).unwrap_or(".");
        match queues.iter_mut().find(|(name, _)| *name == dir) {
            Some((_, files)) => files.push(entry),
            None => queues.push((dir, vec![entry])),
        }
    }
    queues.sort_by(|a, b| a.0.cmp(b.0));

    fn name_of(entry: &FileEntry) -> &str {
        entry
            .path
            .rsplit_once('/')
            .map(|(_, f)| f)
            .unwrap_or(&entry.path)
    }

    // Floor: one heading per directory, one bare filename per file.
    let skeleton: usize = queues
        .iter()
        .map(|(dir, files)| {
            dir.len() + 24 + files.iter().map(|e| name_of(e).len() + 5).sum::<usize>()
        })
        .sum();

    if skeleton > budget {
        return directories_only(&queues);
    }
    budget -= skeleton;

    // Spend what is left on symbol lists, best-ranked first, so the files
    // most worth opening are the ones described in most detail.
    let mut ranked: Vec<&FileEntry> = entries.iter().collect();
    ranked.sort_by(|a, b| {
        b.score
            .partial_cmp(&a.score)
            .unwrap_or(std::cmp::Ordering::Equal)
            .then_with(|| a.path.cmp(&b.path))
    });

    let mut detail: HashMap<&str, Vec<&str>> = HashMap::new();
    for entry in ranked {
        let mut shown: Vec<&str> = Vec::new();
        for symbol in entry.symbols.iter().take(MAX_SYMBOLS_PER_FILE) {
            let cost = symbol.len() + 2;
            if cost > budget {
                break;
            }
            budget -= cost;
            shown.push(symbol);
        }
        if !shown.is_empty() {
            detail.insert(entry.path.as_str(), shown);
        }
        if budget == 0 {
            break;
        }
    }

    let mut out = String::from(header);
    for (dir, files) in &queues {
        out.push_str(&format!("`{dir}/` — {} files\n", files.len()));
        for entry in files {
            let name = name_of(entry);
            match detail.get(entry.path.as_str()) {
                Some(shown) => {
                    let extra = entry.symbols.len().saturating_sub(shown.len());
                    out.push_str(&format!("  {name}: {}", shown.join(", ")));
                    if extra > 0 {
                        out.push_str(&format!(", +{extra} more"));
                    }
                    out.push('\n');
                }
                // Listed without detail: still findable, still not absent.
                None => out.push_str(&format!("  {name}\n")),
            }
        }
    }
    out
}

/// The last resort for a workspace too large to name every file in.
///
/// Complete at the directory level rather than partial at the file level: a
/// reader can still see the whole shape and knows exactly where to look, and
/// nothing here can be mistaken for "that does not exist".
fn directories_only(queues: &[(&str, Vec<&FileEntry>)]) -> String {
    // Its own header: the file-level one promises that a missing path means a
    // missing file, and that promise cannot be kept here.
    let mut out = String::from(
        "## Repository map\n\nThis workspace is too large to list file by file, so only directories and \
their file counts are shown. Every directory is here, but individual files \
are not — use `glob` and `grep` to reach them, and do not read a file's \
absence from this list as evidence it does not exist.\n\n",
    );
    for (dir, files) in queues {
        out.push_str(&format!("`{dir}/` — {} files\n", files.len()));
    }
    out
}

#[derive(Clone, Copy, PartialEq, Eq, Debug)]
enum Language {
    Rust,
    TypeScript,
    Python,
    Go,
    Java,
    C,
    Ruby,
}

fn language_of(path: &Path) -> Option<Language> {
    match path.extension()?.to_str()? {
        "rs" => Some(Language::Rust),
        "ts" | "tsx" | "js" | "jsx" | "mjs" => Some(Language::TypeScript),
        "py" => Some(Language::Python),
        "go" => Some(Language::Go),
        "java" | "kt" => Some(Language::Java),
        "c" | "h" | "cc" | "cpp" | "hpp" => Some(Language::C),
        "rb" => Some(Language::Ruby),
        _ => None,
    }
}

/// Top-level declarations in `text`.
///
/// Line-oriented and deliberately conservative: this runs over a whole
/// repository at session start, so it must be fast and must never block on a
/// language server. It over-reports slightly on unusual formatting, which
/// costs a few wasted characters, and under-reports on macro-generated code,
/// which is what `lsp_symbols` is for.
fn declarations(text: &str, language: Language) -> Vec<String> {
    let mut found = Vec::new();
    for raw in text.lines() {
        let line = raw.trim();
        if line.is_empty()
            || line.starts_with("//")
            || line.starts_with('#') && language != Language::Python
        {
            continue;
        }
        // Only top-level and one level of nesting: deeper is implementation.
        let indent = raw.len() - raw.trim_start().len();
        if indent > 4 {
            continue;
        }
        if let Some(name) = declaration_name(line, language) {
            if !found.contains(&name) {
                found.push(name);
            }
        }
    }
    found
}

fn declaration_name(line: &str, language: Language) -> Option<String> {
    let keywords: &[&str] = match language {
        Language::Rust => &[
            "pub fn ",
            "pub async fn ",
            "pub struct ",
            "pub enum ",
            "pub trait ",
            "pub type ",
            "impl ",
            "macro_rules! ",
        ],
        Language::TypeScript => &[
            "export function ",
            "export async function ",
            "export class ",
            "export interface ",
            "export type ",
            "export const ",
            "export enum ",
        ],
        Language::Python => &["def ", "class ", "async def "],
        Language::Go => &["func ", "type "],
        Language::Java => &[
            "public class ",
            "public interface ",
            "public enum ",
            "class ",
            "interface ",
            "fun ",
        ],
        Language::C => &["struct ", "typedef struct ", "enum "],
        Language::Ruby => &["def ", "class ", "module "],
    };

    for keyword in keywords {
        if let Some(rest) = line.strip_prefix(keyword) {
            let name: String = rest
                .chars()
                .take_while(|c| c.is_alphanumeric() || *c == '_' || *c == '$')
                .collect();
            if name.len() >= 2 {
                return Some(name);
            }
        }
    }
    None
}

// ── the map as a tool ─────────────────────────────────────────────────────────

use crate::workspace::Workspace;
use async_trait::async_trait;
use eventage::agent::{AgentError, Tool};
use eventage::llm::ToolDefinition;
use serde_json::{json, Value};
use std::sync::Arc;

/// Rebuild the repository map on demand.
///
/// The map in the system prompt is a snapshot taken when the session opened,
/// and it is there deliberately: it sits in the stable prefix, which is what
/// makes it cacheable, and regenerating it every turn would invalidate the
/// prompt cache on every request for a file listing that rarely changes.
///
/// That leaves it wrong after the agent adds, deletes or renames files — in a
/// long session it can end up reasoning from names that no longer exist. So
/// the fix is not to move the map into the growing part of the context, it is
/// to let the agent ask for a fresh one when it has reason to think the
/// snapshot has aged.
pub struct RepoMap {
    pub ws: Arc<Workspace>,
}

#[async_trait]
impl Tool for RepoMap {
    fn definition(&self) -> ToolDefinition {
        ToolDefinition::function(
            "repo_map",
            "Rebuild the map of the repository. The map in your instructions was taken \
             when this session started; call this after you or anyone else has added, \
             deleted or renamed files, or whenever a path in it turns out not to exist.",
            json!({
                "type": "object",
                "properties": {
                    "path": {
                        "type": "string",
                        "description": "Map only this subtree; omit for the whole repository"
                    }
                }
            }),
        )
    }

    async fn execute(&self, args: Value) -> Result<Value, AgentError> {
        let sub = args.get("path").and_then(|v| v.as_str()).unwrap_or("");
        let root = self
            .ws
            .confined_dir(sub)
            .await
            .map_err(|e| AgentError::Tool(format!("{e:#}")))?;

        let map = tokio::task::spawn_blocking(move || build(&root, 3_000))
            .await
            .map_err(|e| AgentError::Tool(format!("map task failed: {e}")))?;

        Ok(json!({
            "map": map,
            "note": "current as of now; the copy in your instructions is from session start",
        }))
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::fs;

    fn workspace(files: &[(&str, &str)]) -> tempfile::TempDir {
        let dir = tempfile::tempdir().unwrap();
        for (path, body) in files {
            let full = dir.path().join(path);
            fs::create_dir_all(full.parent().unwrap()).unwrap();
            fs::write(full, body).unwrap();
        }
        dir
    }

    #[test]
    fn lists_what_each_file_declares() {
        let dir = workspace(&[(
            "src/tools.rs",
            "pub struct ReadFile { }\npub fn execute() {}\npub trait Tool {}\n",
        )]);
        let map = build(dir.path(), 2000);
        assert!(map.contains("tools.rs"), "{map}");
        assert!(map.contains("ReadFile"));
        assert!(map.contains("execute"));
        assert!(map.contains("Tool"));
    }

    #[test]
    fn skips_files_that_declare_nothing() {
        let dir = workspace(&[
            ("src/real.rs", "pub fn work() {}\n"),
            ("src/empty.rs", "// just a comment\nlet x = 1;\n"),
        ]);
        let map = build(dir.path(), 2000);
        assert!(map.contains("real.rs"));
        assert!(!map.contains("empty.rs"));
    }

    #[test]
    fn respects_gitignore_so_build_output_stays_out() {
        let dir = workspace(&[
            (".gitignore", "target/\n"),
            ("src/main.rs", "pub fn main() {}\n"),
            ("target/generated.rs", "pub fn generated() {}\n"),
        ]);
        let map = build(dir.path(), 4000);
        assert!(map.contains("main.rs"));
        assert!(
            !map.contains("generated"),
            "ignored paths must not appear: {map}"
        );
    }

    #[tokio::test]
    async fn the_map_tool_reflects_files_created_since_the_session_opened() {
        // The staleness this exists for: the snapshot in the system prompt
        // cannot see anything created after it was taken.
        let dir = tempfile::tempdir().unwrap();
        std::fs::create_dir_all(dir.path().join("src")).unwrap();
        std::fs::write(dir.path().join("src/old.rs"), "pub fn old() {}\n").unwrap();

        let ws = Arc::new(Workspace::open(dir.path()).unwrap());
        let tool = RepoMap { ws: ws.clone() };

        let before = tool.execute(json!({})).await.unwrap();
        assert!(before["map"].as_str().unwrap().contains("old.rs"));
        assert!(!before["map"].as_str().unwrap().contains("added_later.rs"));

        ws.write("src/added_later.rs", "pub fn added() {}\n")
            .await
            .unwrap();

        let after = tool.execute(json!({})).await.unwrap();
        assert!(
            after["map"].as_str().unwrap().contains("added_later.rs"),
            "{}",
            after["map"]
        );
    }

    #[tokio::test]
    async fn the_map_tool_cannot_be_pointed_outside_the_workspace() {
        let dir = tempfile::tempdir().unwrap();
        let ws = Arc::new(Workspace::open(dir.path()).unwrap());
        assert!(RepoMap { ws }
            .execute(json!({ "path": "../.." }))
            .await
            .is_err());
    }

    #[test]
    fn agentignore_can_put_back_a_file_git_ignores() {
        // What git ignores and what an agent should ignore are different
        // questions. A generated client that everyone reads and nobody
        // commits belongs on the map.
        let dir = workspace(&[
            (".gitignore", "generated/\n"),
            (".agentignore", "!generated/\n"),
            ("src/main.rs", "pub fn main() {}\n"),
            ("generated/api_client.rs", "pub fn fetch_user() {}\n"),
        ]);
        let map = build(dir.path(), 4000);
        assert!(
            map.contains("fetch_user"),
            "an .agentignore negation must overrule .gitignore:\n{map}"
        );
    }

    #[test]
    fn agentignore_can_also_hide_something_git_tracks() {
        // The other direction: a committed fixture corpus is noise to an
        // agent even though git rightly keeps it.
        let dir = workspace(&[
            (".agentignore", "fixtures/\n"),
            ("src/main.rs", "pub fn main() {}\n"),
            ("fixtures/sample.rs", "pub fn fixture_case_one() {}\n"),
        ]);
        let map = build(dir.path(), 4000);
        assert!(map.contains("main"));
        assert!(!map.contains("fixture_case_one"), "{map}");
    }

    #[test]
    fn skips_files_that_say_they_were_machine_written() {
        let dir = workspace(&[
            ("src/hand.rs", "pub fn written_by_a_person() {}\n"),
            (
                "src/schema.rs",
                "// Code generated by protoc. DO NOT EDIT.\npub struct Wire {}\n",
            ),
        ]);
        let map = build(dir.path(), 4000);
        assert!(map.contains("written_by_a_person"));
        assert!(!map.contains("Wire"), "generated files are noise: {map}");
    }

    #[test]
    fn a_guarded_folder_inside_the_workspace_is_never_opened() {
        // The macOS report this exists for: the desktop app, started from
        // Finder with no project, falls back to $HOME, and the session's map
        // walked into Music, Desktop and Downloads — one system consent
        // dialog each, from an app the user had only just opened.
        let dir = workspace(&[
            ("src/main.rs", "pub fn main() {}\n"),
            ("Music/library.rs", "pub fn now_playing() {}\n"),
        ]);
        let entries = collect_within(dir.path(), vec![dir.path().join("Music")]);
        let paths: Vec<&str> = entries.iter().map(|e| e.path.as_str()).collect();
        assert_eq!(paths, ["src/main.rs"], "the guarded folder was read");
    }

    #[test]
    fn a_guarded_folder_chosen_as_the_workspace_is_still_mapped() {
        // Pruning the root would map nothing at all. Someone who opens
        // ~/Documents means it, and the one prompt is answerable because they
        // can see what they just clicked.
        let dir = workspace(&[("notes/plan.rs", "pub fn plan() {}\n")]);
        let entries = collect_within(dir.path(), vec![dir.path().to_path_buf()]);
        assert_eq!(entries.len(), 1, "the chosen workspace was pruned");
    }

    #[test]
    fn a_project_inside_a_guarded_folder_is_left_alone() {
        // The walk starts below the door and never meets it, so the guard has
        // nothing to say about ~/Documents/project.
        let home = Path::new("/Users/you");
        let guarded = vec![home.join("Documents")];
        let project = home.join("Documents/project");
        assert!(!is_guarded(&project, &project.join("src"), &guarded));
    }

    #[test]
    fn skips_vendored_directories_even_when_committed() {
        let dir = workspace(&[
            ("src/app.rs", "pub fn app() {}\n"),
            ("vendor/lib/big.rs", "pub fn vendored_helper() {}\n"),
            ("third_party/dep.go", "func VendoredGo() {}\n"),
        ]);
        let map = build(dir.path(), 4000);
        assert!(map.contains("app"));
        assert!(!map.contains("vendored_helper"), "{map}");
        assert!(!map.contains("VendoredGo"), "{map}");
    }

    #[test]
    fn no_file_is_ever_dropped_to_save_space() {
        // The bug this shape exists to prevent: `src/llm/content.rs` was cut
        // under a budget, and an agent that read the map concluded the
        // multimodal support defined in it did not exist. Detail is
        // negotiable; the existence of a file is not.
        let mut files: Vec<(String, String)> = Vec::new();
        for i in 0..60 {
            files.push((
                format!("src/mod{i}.rs"),
                (0..20)
                    .map(|j| format!("pub fn a_fairly_long_symbol_name_{i}_{j}() {{}}\n"))
                    .collect(),
            ));
        }
        let refs: Vec<(&str, &str)> = files
            .iter()
            .map(|(p, b)| (p.as_str(), b.as_str()))
            .collect();
        let dir = workspace(&refs);

        // A budget far too small for the symbols, ample for the paths.
        let map = build(dir.path(), 400);
        for i in 0..60 {
            assert!(
                map.contains(&format!("mod{i}.rs")),
                "mod{i}.rs vanished:\n{map}"
            );
        }
        // And it spent what it had on detail for the best-ranked files.
        assert!(map.contains("a_fairly_long_symbol_name"), "{map}");
    }

    #[test]
    fn the_map_states_that_a_missing_path_means_a_missing_file() {
        let dir = workspace(&[("a.rs", "pub fn go() {}\n")]);
        let map = build(dir.path(), 2000);
        assert!(
            map.contains("if a path is not here, it is not in the\nworkspace")
                || map.contains("it is not in the"),
            "{map}"
        );
    }

    #[test]
    fn an_enormous_workspace_degrades_to_directories_not_to_silence() {
        // Past the point where even bare paths fit, the map must stay
        // complete at *some* level rather than become a partial file list.
        let mut files: Vec<(String, String)> = Vec::new();
        for d in 0..40 {
            for f in 0..40 {
                files.push((
                    format!("area{d}/component{f}/implementation_module.rs"),
                    "pub fn work() {}\n".into(),
                ));
            }
        }
        let refs: Vec<(&str, &str)> = files
            .iter()
            .map(|(p, b)| (p.as_str(), b.as_str()))
            .collect();
        let dir = workspace(&refs);

        let map = build(dir.path(), 300);
        assert!(map.contains("too large to list file by file"), "{map}");
        // And it must not inherit the promise it cannot keep.
        assert!(!map.contains("if a path is not here"), "{map}");
        assert!(map.contains("do not read a file's absence"), "{map}");
        assert!(map.contains("`area0/component0/` — 1 files"), "{map}");
        // Every directory still accounted for.
        for d in [0, 17, 39] {
            assert!(map.contains(&format!("area{d}/")), "area{d} missing");
        }
    }

    #[test]
    fn caps_the_symbols_shown_per_file() {
        let body: String = (0..40).map(|i| format!("pub fn f{i}() {{}}\n")).collect();
        let dir = workspace(&[("src/big.rs", body.as_str())]);
        let map = build(dir.path(), 4000);
        assert!(map.contains("more"), "{map}");
    }

    #[test]
    fn reads_the_common_languages() {
        let dir = workspace(&[
            (
                "a.ts",
                "export function hello() {}\nexport class Thing {}\n",
            ),
            ("b.py", "def compute():\n    pass\nclass Model:\n    pass\n"),
            ("c.go", "func Handler() {}\ntype Config struct{}\n"),
        ]);
        let map = build(dir.path(), 4000);
        for name in ["hello", "Thing", "compute", "Model", "Handler", "Config"] {
            assert!(map.contains(name), "missing {name} in {map}");
        }
    }

    #[test]
    fn an_empty_workspace_yields_no_map_rather_than_a_header() {
        let dir = workspace(&[("README.md", "# nothing to index\n")]);
        assert!(build(dir.path(), 2000).is_empty());
    }

    #[test]
    fn ignores_bodies_so_local_names_do_not_leak_in() {
        let dir = workspace(&[(
            "src/a.rs",
            "pub fn outer() {\n        pub fn deeply_nested_helper() {}\n}\n",
        )]);
        let map = build(dir.path(), 2000);
        assert!(map.contains("outer"));
        assert!(!map.contains("deeply_nested_helper"), "{map}");
    }
}
